### ISSUE TITLE
Q: can public-assets be generated or be a directory?

### ISSUE THREAD

**Issue by basz** [basz/shoelace-ember#1]
Ideally this would copy a directory but i could not het something like `/**/*.svg` to work...

https://github.com/basz/shoelace-ember/blob/main/%40shoelace-style/ember/package.json#L97

**Comment by NullVoxPopuli** [comment]
I don't think you need to specify anything with public-assets -- you may import SVGs in to JS and use them as URLs (or sprites), depending on the consumer's build configuration

**Comment by basz** [comment]
to go public-assets less this should work no?

// index.ts

``` ts
import icon from '@shoelace-style/shoelace/dist/assets/icons/browser-chrome.svg';

[start:*test-app] Module not found: Error: Package path ./dist/assets/icons/browser-chrome.svg is not exported from package /Users/bas/Documents/Projects/Bushbaby.EmberShoelace/@shoelace-style/ember/node_modules/@shoelace-style/shoelace (see exports field in /Users/bas/Documents/Projects/Bushbaby.EmberShoelace/@shoelace-style/ember/node_modules/@shoelace-style/shoelace/package.json)
[start:*test-app]  @ ./app.ts 6:0-31
[start:*test-app]  @ ./assets/test-app.js 7:13-39 84:6-23
[start:*test-app] 
[start:*test-app] webpack 5.88.1 compiled with 1 error in 3098 ms
[start:*test-app] Build Error (PackagerRunner) in ../../../../@shoelace-style/ember/dist/index.js
[start:*test-app] 
[start:*test-app] Module not found: Error: Package path ./dist/assets/icons/browser-chrome.svg is not exported from package /Users/bas/Documents/Projects/Bushbaby.EmberShoelace/@shoelace-style/ember/node_modules/@shoelace-style/shoelace (see exports field in /Users/bas/Documents/Projects/Bushbaby.EmberShoelace/@shoelace-style/ember/node_modules/@shoelace-style/shoelace/package.json)

```

In addition I have a hard time imagining how `<sl-icon name="browser-chrome"></sl-icon>` (which depends on `setBasePath`) translates to a url from an import '@shoelace-style/shoelace/dist/assets/icons/browser-chrome.svg'. In other words; how would the mapping work from import to url?
I don't really understand webpack's magic unfortunately.

**Comment by basz** [comment]
I did just find rollup.publicAsset new to @embroider/addon-dev v4 which syncs a public dir with the public-assets metadata in package, so that's something...

https://github.com/embroider-build/embroider/blob/main/packages/addon-dev/src/rollup.ts#L94

**Comment by NullVoxPopuli** [comment]
Your consuming app needs to have an svg handling plugin
Like here: https://github.com/NullVoxPopuli/ember-icons/pull/1/files?file-filters%5B%5D=.md&file-filters%5B%5D=dotfile&show-deleted-files=true&show-viewed-files=true#diff-5ac1dbc5d580c97bd07a4bd51e6bbc18bc1f4fb30554237319502d7400b905beR6
